type movable;;
type fixed;;
type collision_type = Null | Horizontal | Vertical;;
type collision;;
type t;;

val sprite_jump_right : Tsdl.Sdl.rect array;;
val sprite_jump_left : Tsdl.Sdl.rect array;;
val null_collision : collision;;

val start_timer_lasers : unit -> unit;;
val get_timer_lasers : unit -> Tsdl.Sdl.uint32;;

val movable_with_constructor : movable -> t;;
val fixed_with_constructor : fixed -> t;;
val move_horizontally : movable -> float -> int -> int -> movable;;
val move_vertically : movable -> float -> int -> int -> movable;;
val right : movable -> movable;;
val left : movable -> movable;;
val stop : movable -> movable;;
val applyGravity : movable -> movable;;
val apply_friction : movable -> movable;;
val change_direction : movable -> movable;;
val jump : movable -> movable;;
val collide : t -> t -> collision;;
val get_damage : movable -> int -> movable;;
val health : movable -> int -> movable;;
val compare : t -> t -> bool;;
val compare_movable : movable -> movable -> bool;;
val compare_fixed : fixed -> fixed -> bool;;
val create_movable : float -> float -> float -> float -> int -> int -> int -> string -> int -> int -> int -> movable;;
val create_enemy : movable -> movable;;
val create_fixed : string -> float -> float -> int -> int -> string -> string -> int -> int -> int -> int -> fixed;;
val create_endlevel : float -> float -> int -> int -> string -> int -> int -> int -> fixed;;
val create_laser : float -> float -> int -> int -> string -> int -> int -> int -> fixed;;
val create_decoration : float -> float -> int -> int -> string -> int -> int -> int -> fixed;;
val create_tile : float -> float -> int -> int -> string -> int -> int -> int -> fixed;;
val store_textures_fixed : fixed -> Tsdl.Sdl.renderer -> unit;;
val create_null_movable : unit -> movable;;
val create_null_fixed : unit -> fixed;;
val select_frame_movable_jump : float -> float -> int -> int -> int -> Tsdl.Sdl.uint32 -> int;;
val select_frame_movable : float -> float -> int -> int -> int -> Tsdl.Sdl.uint32 -> float -> int;;
val select_frame_fixed : int -> int -> int -> Tsdl.Sdl.uint32 -> int -> string -> int;;
val reset_frame_jump : movable -> unit;;
val enable_jump : movable -> movable;;
val disable_jump : movable -> movable;;
val free : t -> unit;;
val free_global_var : unit -> unit;;
val is_dead : movable -> bool;;
val get_id : t -> int;;
val get_subtype : t -> string;;
val get_positionX : t -> float;;
val get_positionY : t -> float;;
val get_speedX : t -> float;;
val get_speedY : t -> float;;
val get_width : t -> int;;
val get_height : t -> int;;
val get_mass : movable -> int;;
val get_life : movable -> int;;
val get_max_life : movable -> int;;
val get_texture : t -> Object_texture.t;;
val get_optionnal_texture : fixed -> Object_texture.t;;
val get_frame : t -> int;;
val get_current_sprite : t -> Tsdl.Sdl.rect;;
val get_sprite_left : t -> Tsdl.Sdl.rect array;;
val get_sprite_right : t -> Tsdl.Sdl.rect array;;
val get_sprite_active : t -> Tsdl.Sdl.rect array;;
val get_sprite_inactive : t -> Tsdl.Sdl.rect array;;
val get_timer : t -> Tsdl.Sdl.uint32;;
val get_zoom : t -> int;;
val get_status : t -> int;;
val get_delay_frame : string -> int;;
val get_max_jump : t -> float;;
val get_jump : t -> float;;
val get_direction : t -> int;;
val get_last_damages_time : t -> Tsdl.Sdl.uint32;;
val get_last_fire_time : t -> Tsdl.Sdl.uint32;;
val animation_stop : t -> bool;;
val to_box : t -> Tsdl.Sdl.rect;;
val set_frame : t -> int -> unit;;
val set_timer : t -> unit;;
val set_positionX : movable -> float -> movable;;
val set_positionY : movable -> float -> movable;;
val set_direction : movable -> int -> movable;;
val set_jump : movable -> float -> movable;;
val set_status : fixed -> int -> unit;;
val change_status : fixed -> unit;;
val set_life : movable -> int -> movable;;
val set_last_fire_time : movable -> unit;;

val get_first_id : collision -> int;;
val get_second_id : collision -> int;;
val get_time : collision -> float;;
val get_damagesA : collision -> int;;
val get_damagesB : collision -> int;;
val get_collision_type : collision -> collision_type;;
