type movable;;
type fixed;;
type collision_type = Null | Horizontal | Vertical;;
type collision;;
type t;;

val null_collision : collision;;

val movable_with_constructor : movable -> t;;
val fixed_with_constructor : fixed -> t;;
val move : movable -> float -> int -> int -> movable;;
val right : movable -> Tsdl.Sdl.uint32 -> movable;;
val left : movable -> Tsdl.Sdl.uint32 -> movable;;
val stop : movable -> movable;;
val applyGravity : movable -> Tsdl.Sdl.uint32 -> movable;;
val apply_friction : movable -> Tsdl.Sdl.uint32 -> movable;;
val change_direction : movable -> movable;;
val jump : movable -> movable;;
val collide : t -> t -> collision;;
val get_damage : movable -> int -> movable;;
val health : movable -> int -> movable;;
val compare : t -> t -> bool;;
val compare_movable : movable -> movable -> bool;;
val compare_fixed : fixed -> fixed -> bool;;
val create_movable : float -> float -> float -> float -> int -> int -> int -> string -> movable;;
val create_fixed : float -> float -> int -> int -> string -> int -> fixed;;
val create_null_movable : unit -> movable;;
val create_null_fixed : unit -> fixed;;
val select_frame_movable : float -> float -> int -> int -> int -> Tsdl.Sdl.uint32 -> int;;
val select_frame_fixed : int -> int -> int -> Tsdl.Sdl.uint32 -> int -> int;;
val get_id : t -> int;;
val get_positionX : t -> float;;
val get_positionY : t -> float;;
val get_speedX : t -> float;;
val get_speedY : t -> float;;
val get_width : t -> int;;
val get_height : t -> int;;
val get_mass : movable -> int;;
val get_life : movable -> int;;
val get_texture : t -> Object_texture.t;;
val get_frame : t -> int;;
val get_current_sprite : t -> Tsdl.Sdl.rect;;
val get_sprite_left : t -> Tsdl.Sdl.rect array;;
val get_sprite_right : t -> Tsdl.Sdl.rect array;;
val get_sprite_active : t -> Tsdl.Sdl.rect array;;
val get_timer : t -> Tsdl.Sdl.uint32;;
val get_zoom : t -> int;;
val get_status : t -> int;;
val set_frame : t -> int -> unit;;
val set_timer : t -> unit;;

val get_first_id : collision -> int;;
val get_second_id : collision -> int;;
val get_time : collision -> float;;
val get_damagesA : collision -> int;;
val get_damagesB : collision -> int;;
val get_collision_type : collision -> collision_type;;
